export const USER_REGISTER = "USER_REGISTER";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const USER_LOGIN = "USER_LOGIN";
export const USER_ALL_USERS = "USER_ALL_USERS";
export const CLEAR_ALL = "CLEAR_ALL";
