export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";
export const GET_ALL_GROUP_MESSAGES = "GET_ALL_GROUP_MESSAGES";
export const GET_ALL_GROUPS = "GET_ALL_GROUPS";
export const GET_ALL_RESPONSE = "GET_ALL_RESPONSE";
export const GET_NEW_GROUP_RESPONSE = "GET_NEW_GROUP_RESPONSE";
export const CLEAR_ALL = "CLEAR_ALL";
